### ISSUE TITLE
found.csv is not there

### ISSUE THREAD

**Issue by ghost** [h0nde/roblox-group-scraper#1]
![image](https://user-images.githubusercontent.com/79235116/109126716-8bd23980-7788-11eb-9e30-a03e34ead180.png)
i ran the bot and after a while i got 101/100 for some reason? i went to check my folders for any found.csv but there isnt.

**Comment by 7rident** [comment]
its only there after you found a group

**Comment by Alektherblxdev** [comment]
> its only there after you found a group

has it worked for you?

**Comment by 7rident** [comment]
yes but afterwards i started getting ddosed by scammers and called by them
